### ISSUE TITLE
Error in reading temporary shapefile

### ISSUE THREAD

**Issue by goergen95** [gisma/uavRst#17]
https://github.com/gisma/uavRst/blob/c786f7a7b1e61e9151afc01831a6f04fd590815d/R/tb_bluedjinn.R#L457

This line throws up an error in Win10 that the data source cannot be opened. 

```Error in ogrListLayers(dsn = dsn) : Cannot open data source```

I think it is because of a wrong positioning of the ```paste0()``` function.
Is it possible to change the line to something like the following: 

```stat1 <- rgdal::readOGR(paste0(path_run,basename(x[i]),"Stat.shp"), verbose = TRUE)```

**Comment by gisma** [comment]
Thanks for pointing out. I think the error occurs due to a wrong shapefile in the tutorial data set, as a result no input shapefile is created or can be read afterwards. The syntax of `readOGR``request a separation between the path and the vector file usually without extension. this should be ok.  Will check it.

**Comment by goergen95** [comment]
I am actually not using the tutorial dataset, but still, this error occurred while using ```treepos_GWS``` which calls ```poly_stat``` internally. At least for my case, it works when specifying the shapefile directly with a filename.
In my understanding of  ```readOGR``` you can choose between either providing a directory or a file name, but not both at the same time as different arguments. At least I don't get it to work that way...
