### ISSUE TITLE
rlas and lidR compatibility

### ISSUE THREAD

**Issue by Jean-Romain** [gisma/uavRst#9]
Hi, I saw that you may plan to release your package soon. I would like to point out minor issues you may encounter with the next release of `rlas` and `lidR`

In `rlas 1.2.0` (not yet on cran) the function `readlasheader` will be replaced by `read.lasheader`. The first one still exists but will be progressively deprecated then removed. Both are identical. this is only for name constancy with new functions `read.las` and `write.las`.

In `lidR 1.5.0 (not yet on cran)` the piping operator `%>%` will not be loaded anymore. I removed the dependency to `magrittr`. If you want to continue to use `%>%` you need to load  `magrittr`. But it is probably not an issue because you don't have anymore a code that use this pipe.

Depending on when you plan to release your package you can wait for an update of `rlas` or consider that you will have to make an update of your package later (in several months).

Regards.

**Comment by gisma** [comment]
@Jean-Romain  thanks for mention this issues. I am planning to release the package during the next  weeks. So probably I will use the current namespaces and keep in mind to adapt it later on.
Due to the fact that `lidR` and  `rlas` are fast evolving I will rewrite the LiDAR data related part of the `uavRst` package using your packages as far as possible.  Thanks for pointing out and providing the packages
cheers Chris

**Comment by Jean-Romain** [comment]
`rlas 1.2.0` is on CRAN.
